info:
  app:
    name: ${name:hocs-casework-search-indexer}
    fullname: Hocs Casework to Search Indexer Service
    version: ${version:0.0.1}

server:
  shutdown: graceful
  port: '8096'
  http2:
    enabled: 'true'

spring:
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: 'false'
        use_sql_comments: 'true'
        temp:
          use_jdbc_metadata_defaults: 'false'
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: ${db.schema.name:casework}
    locations: classpath:/db/migration/postgresql
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:postgres}?currentSchema=${db.schema.name:casework}&user=${db.username:root}&password=${db.password:dev}&stringtype=unspecified

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true


batch-size: 200