info:
  app:
    name: ${name:hocs-casework-search-indexer}
    fullname: Hocs Casework to Search Indexer Service
    version: ${version:0.0.1}

spring:
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: 'false'
        use_sql_comments: 'true'
        temp:
          use_jdbc_metadata_defaults: 'false'
        format_sql: 'true'
        show_sql: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:postgres}?currentSchema=${db.schema.name:casework}&user=${db.username:root}&password=${db.password:dev}&stringtype=unspecified

app:
  mode: MULTIPLE
  create:
    enabled: true
    baseline:
    prefix:
    timestamp:
  migrate:
    enabled: true
    batch:
      size: 1000
      interval: 200
    startDate:
    endDate:
    types:
    offset: 0
