---
hocs-backend-service:
  nameOverride: hocs-casework-search-indexer

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-casework-search-indexer
    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
      requests:
        memory: 2048Mi
