---

app:
  image:
    repository: quay.io/ukhomeofficedigital/hocs-casework-search-indexer
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 2000m
      memory: 2048Mi
  mode: SINGULAR
  newIndex: 'false'
  batchSize: '200'
  batchInterval: '500'
  elasticPrefix: '{{ .Release.Namespace }}-latest'


