---
app:
  image:
    repository: quay.io/ukhomeofficedigital/hocs-casework-search-indexer
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 2000m
      memory: 2048Mi
  mode: SINGULAR
  index:
    baseline:
    prefix:
  batch:
    size: '200'
    interval: '500'
  dataCreatedBefore:
