---
app:
  image:
    repository: quay.io/ukhomeofficedigital/hocs-casework-search-indexer
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 2000m
      memory: 2048Mi
  mode: 'MULTIPLE'
  create:
    enabled: 'true'
    baseline:
    prefix:
    timestamp:
  migrate:
    enabled: 'true'
    batch:
      size: '100'
      interval: '5000'
    startDate:
    endDate:
    types:
    offset:
