---
hocs-backend-service:
  minReplicas: 1
  maxReplicas: 1

  deploymentAnnotations: { }

  app:
    resources:
      limits:
        cpu: 300m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 768Mi
