name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/test-gradle.yml@v2
    with:
      dockerComposeComponents: 'localstack postgres'
      dockerComposeCommand: './ci/docker-compose.yml -f ./ci/docker-compose.elastic.yml'
    secrets: inherit
